gaps inner 4
gaps outer 2
smart_gaps off
default_border pixel 1
smart_borders on
titlebar_padding 8 4
font pango:Adwaita Sans 10
output * bg /usr/share/backgrounds/default-dark.jxl fill

input "type:touchpad" {
    pointer_accel 0.25
    accel_profile "adaptive"
    tap enabled
    natural_scroll enabled
    dwt enabled
}

client.focused          #89b4fa #89b4fa #1e1e2e #f5c2e7 #89b4fa
client.focused_inactive #45475a #45475a #cdd6f4 #45475a #45475a
client.unfocused        #313244 #1e1e2e #a6adc8 #313244 #313244
client.urgent           #f38ba8 #f38ba8 #1e1e2e #f38ba8 #f38ba8
