unbindsym $mod+d
bindsym $mod+d exec ~/.local/bin/rofi-toggle launcher rofi -show drun -theme ~/.config/rofi/launcher.rasi
bindsym Mod1+Tab exec ~/.local/bin/rofi-toggle window rofi -show window

bindsym $mod+Tab workspace next
bindsym $mod+Shift+Tab workspace prev
bindsym --whole-window $mod+button5 workspace next
bindsym --whole-window $mod+button4 workspace prev

bindsym $mod+q kill

bindsym $mod+Shift+v exec ~/.local/bin/rofi-toggle clipboard ~/.local/bin/clip-menu

bindsym $mod+Escape exec ~/.local/bin/rofi-toggle power ~/.local/bin/power-menu
bindsym $mod+Shift+s exec grimshot --notify savecopy area
bindsym $mod+period exec ~/.local/bin/rofi-toggle emoji ~/.local/bin/emoji-menu
bindsym $mod+n exec ~/.local/bin/nightlight-toggle
bindsym $mod+Shift+t exec ~/.local/bin/theme-toggle
bindsym $mod+Shift+w exec ~/.local/bin/rofi-toggle wallpaper ~/.local/bin/wallpaper-menu

exec_always ~/.local/bin/clip-watch
exec ~/.local/bin/first-run
exec ~/.local/bin/wallpaper-menu --warm

bindsym $mod+slash exec ~/.local/bin/rofi-toggle keys ~/.local/bin/keys-menu

unbindsym XF86MonBrightnessUp
unbindsym XF86MonBrightnessDown
bindsym --locked XF86MonBrightnessUp exec ~/.local/bin/brightness +5
bindsym --locked XF86MonBrightnessDown exec ~/.local/bin/brightness -5

bindgesture swipe:3:right workspace next
bindgesture swipe:3:left workspace prev
bindgesture swipe:4:right focus next
bindgesture swipe:4:left focus prev
