# Edit, then run: apply-defaults
terminal=foot
browser=brave-origin
file_manager=thunar
text_editor=org.gnome.TextEditor
code_editor=org.gnome.TextEditor
# terminal $EDITOR, separate from GUI text_editor
terminal_editor=vim
image_viewer=imv
image_editor=
video_player=io.mpv.Mpv
audio_player=io.mpv.Mpv
pdf_viewer=brave-origin
ebook_reader=
word_processor=
spreadsheet=
presentation=
archive_manager=xarchiver
torrent_client=
mail_client=
calendar=
contacts=
markdown_viewer=
json_viewer=
xml_viewer=
yaml_viewer=
font_viewer=
messaging=
telephony=
remote_desktop=
feed_reader=
